### PR TITLE
build(web): fail vite build on a browser-externalized Node built-in (#1769)

### LINKED ISSUE #1769: Build gate: fail vite build on a browser-externalized Node built-in (SEP of #1615)
## Motivation

Follow-up from #1615 / PR #1768. While adding the headless-browser boot smoke, we measured what the pinned **vite@8.0.0** actually does when a Node built-in reaches the browser graph:

- A `node:*` (or bare builtin via a dep's `browser` field) import is **externalized at build time with a warning** (`plugin rolldown:vite-resolve`: `Module "node:fs" has been externalized for browser compatibility`), and the build **still succeeds**, shipping a silent `module.exports = {}` stub.
- CI does **not** fail on that warning, so nothing upstream of the runtime gates it.

Consequences:
- **CASE 1** (the stub is *called* at module init): crashes the app at runtime → caught by `smoke:web:browser` (#1615). That smoke is currently the *only* gate for this shape.
- **CASE 2** (the stub is imported but never *called*): ships a harmless `{}` and is invisible to the browser smoke by design — nothing catches it.

## Proposal

Make `vite build` treat that specific browser-externalization warning as an **error** (e.g. via an `onwarn`/`onLog` hook in `clients/web/vite.config.ts`, or Rolldown's warning-to-error mechanism). That would:
- move CASE 1 detection **upstream** of the smoke into `npm run build` / `validate` (a Node built-in in the browser graph fails the build instead of shipping a broken bundle), and
- additionally catch **CASE 2**, which the runtime smoke cannot see.

The browser smoke stays valuable as the runtime backstop (it catches crashes the build can't reason about), but the build gate is the cheaper, earlier, more complete catch for the externalization class specifically.

## Notes
- Verify the exact warning code/shape emitted by the pinned Vite (it differs across 8.0.x → 8.1.x — 8.1.5 reportedly fails the build outright, 8.0.0 warns), and key the gate off something stable.
- Keep it scoped to *browser*-target builds; the Node runner build legitimately uses built-ins.

Discovered during the review of PR #1768.

### PR DESCRIPTION
**Pull request by cliffhall**
Closes #1769

## Problem

Follow-up from #1615 / PR #1768. Vite 8 (rolldown), when a `node:*` / bare Node built-in reaches the browser graph, **externalizes it with a warning and still succeeds the build**, shipping a `module.exports = {}` stub:

- **CASE 1** — the stub is *called* at module init → crashes at runtime → caught by `smoke:web:browser` (#1615), but only there, and only at runtime.
- **CASE 2** — the stub is imported but never *called* → ships a harmless-looking `{}` and is **invisible to the runtime smoke by design** → nothing gates it.

## Fix

A Vite build plugin turns that specific browser-externalization warning into a hard `vite build` error, so a Node built-in in the browser graph now **fails `npm run build` / `validate`** — upstream of the smoke, and covering **both** cases.

- **`clients/web/server/browser-externalized-builtin-gate.ts`** — the Vite-agnostic logic (phrase match, error, per-build state machine). Unit-tested to the ≥90 gate; no Vite import, so it's trivially testable.
- **`clients/web/vite.config.ts`** — the thin Vite wiring. Key subtlety: **throwing inside rolldown's `onLog` is swallowed** (it's the one hook where a thrown error doesn't abort the build — verified against `vite@8.0.0`). So the gate *records* the warning in `onLog` and **re-throws in `buildEnd`**, where a throw aborts the build with a non-zero exit. Scoped to `vite build` (`apply: 'build'`) — never `vite dev` or the vitest projects; the Node runner build (tsup, `build:runner`) is a separate config where built-ins are legitimate.

## Guarding the version-drift risk the issue calls out

There is **no stable log `code`** on the rolldown warning (it carries only `message` + `plugin: "rolldown:vite-resolve"` — captured against `vite@8.0.0`), so the gate keys off the documented message phrasing (`…has been externalized for browser compatibility`). The issue notes this phrasing **differs across Vite releases** and could silently disable a message-keyed gate.

**`scripts/verify-build-gate.mjs`** (`npm run verify:build-gate`, wired into `npm run ci` and the GitHub workflow) closes that: it forces a `node:fs` import into `src/main.tsx`, runs a **real** `vite build`, and asserts the build **fails via the #1769 gate** — then restores the entry. The unit tests cover the detection logic against a captured string; only this real build catches a live-Vite phrasing drift. `smoke:web:browser` stays as the runtime backstop for crashes the build can't reason about.

## Verification

- `vite build` with a Node built-in in the browser graph → **fails** with the actionable #1769 error (exit 1). ✓
- Clean `vite build` of the real app → **succeeds**, other warnings (chunk-size) still print. ✓
- `npm run verify:build-gate` → OK, and leaves `src/main.tsx` clean. ✓
- Full `npm run ci` green locally (validate, coverage gate incl. the new module, `verify:build-gate`, smoke, Storybook).

## Docs

Updated `AGENTS.md` (build-gate section next to `smoke:web:browser`), the root `README.md` testing table, and the CI workflow.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01XNdjEPKLG637X8YmhDiEk5

### CODE REVIEW

**Comment by cliffhall** [comment]
@claude review

**Comment by cliffhall** [comment]
Thanks — thorough review. Addressed all of 1–5 plus the nits in `011efbab`.

**1. Per-build state / sticky failure under watch — fixed.** Added `reset()` to the gate and call it from a `buildStart` hook, so a `vite build --watch` rebuild starts fresh instead of failing forever on an already-fixed import. Added a `reset()` unit test, and the docblock now describes the plugin resetting in `buildStart` rather than claiming per-instance freshness.

**2. `buildEnd` masking a real build error — fixed.** `buildEnd(error)` now only calls `assertClean()` on the success path (`if (!error)`), so an unrelated failure (syntax error, unresolved import) surfaces as itself instead of being overwritten by the #1769 message. `verify:build-gate` is unaffected — the probe build has no other error, so the gate is still what fails it (re-verified).

**3. `rm -rf` — removed entirely.** I tested the reviewer's question directly: the gate fires reliably **without** any cache clear (two consecutive probe builds both failed with #1769, no clearing). My original "caching" concern was a misdiagnosis — it was actually the `onLog`-swallow behavior before I moved the throw to `buildEnd`. So rather than swap to `rmSync`, I dropped the cache-clear (and the `viteCache` var) altogether: no Windows-hostile `rm`, and no re-optimize papercut for the next `npm run dev`.

**4. Spawn-failure misdiagnosis — fixed.** Added an explicit `result.error` check (mirroring `ensure-web-build.ts`) that fails with the spawn error itself, before the `status === 0` / `#1769` branches.

**5. Docs — fixed.** Added `browser-externalized-builtin-gate.ts` to the `AGENTS.md` project-structure `server/` block and the `clients/web/README.md` `server/` bullet list — the latter with a sentence on *why* a build-config helper lives under `server/` (Node-only, build-time tooling imported by the Vite config, never the browser, alongside the other `vite-*` helpers). Added `verify-build-gate` to the root README `scripts/` line.

**6. Nits:**
- **Interrupt safety** — added `SIGINT`/`SIGTERM` handlers that restore `src/main.tsx` and exit, so a Ctrl-C during the build no longer leaves the entry mutated.
- **Progress log** — added a "running a real vite build (takes a minute)…" line before the spawn.
- **Quote style** — switched the new module to double quotes to match its `server/` siblings. (Agreed the underlying gap is that `clients/web`'s `format:check` only covers `src/`, leaving `server/` + `vite.config.ts` ungated — I've left that broader gap alone here.)
- **Wrap width** — reflowed the over-long line.

Good catch on the `apply: 'build'` → Storybook build also getting the gate; that's intended and welcome.

`npm run ci` is green locally (validate, coverage incl. the new module, `verify:build-gate`, smoke, Storybook). Will re-request review once CI clears on the new commit.

**Comment by cliffhall** [comment]
@claude review

**Comment by cliffhall** [comment]
Round-2 addressed in `a8a368a7` — took all four substantive points plus the nits.

**1. Stale `ci` enumerations in `AGENTS.md` — fixed.** Updated both pipeline enumerations (the "mandatory pre-push" line and the "CI runs…" line) to include `verify:build-gate`, and dropped the now-false "Storybook is the only CI step left out" claim. Good catch that this is the exact file someone would use to "correct" `package.json` back.

**2. `npx` running a different Vite than pinned — fixed.** Switched to `npx --no-install vite build`, so the check can never silently fetch a registry Vite when `clients/web/node_modules` is missing/partial — a missing local bin now surfaces via the `result.error` branch instead. Added a comment explaining why version fidelity specifically matters here (it's the whole point of the script). Agreed the plain-`npx` convention in the other smokes is fine because they don't carry version-fidelity semantics.

**3. Environment scoping — fixed.** Added `applyToEnvironment: (env) => env.name === 'client'` so the gate is structurally browser-only; a future SSR/node environment built from this config won't be failed for a legitimate `node:*` import. Verified the gate still fires for the client build (`verify:build-gate` green) and the clean build still passes (smoke). Noted the browser scoping in the module docblock too.

**4. Report all offenders — done.** The gate now collects every matched warning (deduped, via a `Set`) and lists them together in the error, so a build leaking several built-ins reports them in one pass rather than one-per-rebuild. `browserExternalizedBuiltinError` takes `string[]`; updated the tests (multi-offender + dedupe cases).

**5. Nits:**
- **Signal-handler comment** — clarified that while `spawnSync` blocks, a Ctrl-C tears down `vite` via the shared process group first (child dies → `spawnSync` returns → `finally` restores), and the handlers are the backstop for a `kill <pid>` that targets only this process.
- **Probe prepend → append** — appended instead (ES imports hoist, so it still externalizes at resolve time, and appending won't demote a future leading directive like `"use client"`).
- **`scripts/` format gap** — left as-is; it's the same pre-existing "not format-gated" class as `server/`, out of scope for this PR.

On the two "what I checked and found fine" notes: yes — the `dist` ordering is safe (the throw is in `buildEnd`, before output/`emptyOutDir`), and CI-green-on-the-commit is the real evidence that `buildStart`'s reset doesn't erase a resolve-time warning.

`npm run ci` is green locally. Will re-request review once CI clears on `a8a368a7`.

**Comment by cliffhall** [comment]
@claude review

**Comment by cliffhall** [comment]
Round-3 addressed in `f4db356a` — took all five findings.

**1. Muddled `AGENTS.md` CI-steps sentence — fixed.** You're right, "the only step … as its own tail step" was false-or-tautological. Replaced with a plain statement: GitHub CI runs the same chain as separate workflow steps, with the Storybook play-function tests last.

**2. Why the real build, not a temp entry — documented.** Agreed the fidelity is the point (a temp config keeps passing when someone deletes the plugin or adds an `onwarn` suppression above it — the exact regressions this exists to catch). Added a docblock paragraph saying so explicitly, ending with "Do NOT optimize it into a temp entry — that silently loses the config-regression coverage," so the next person eyeing the minute-long build doesn't quietly trade the property away. Kept the real-config approach.

**3. Transitive-dependency escape hatch — error message extended.** The remedy text now covers the case where the `node:*` import comes from a dependency, not first-party code: add a `resolve.alias` in `vite.config.ts` pointing the module at a browser shim (referencing the module path in the warning). I went with the message rather than the `allow: [...]` option — it's latent (repo builds clean today), and adding config API + tests for an unhit path felt like speculative surface; the actionable error turns the dead-end into a fix, and the allowlist is a clean follow-up if someone actually hits it.

**4. Verify-script robustness — both fixed.**
- Guarded the entry read: a renamed/missing `main.tsx` now fails through `fail()` with an actionable message (and a note that the path is hardcoded here) instead of a raw ENOENT stack.
- Restore-failure remedy no longer recommends `git checkout --` (which discards uncommitted edits). It now writes the captured original to a sidecar `.bak` and points there — the honest remedy, since the script is holding the correct content and this message only prints when something already went wrong.

**5. Nits:**
- **Redundant guard — removed, properly.** Rather than just dropping `message !== undefined` (which would break the `Set<string>.add()` typing), I made `isBrowserExternalizedBuiltinLog` a `message is string` type guard, so `recordLog` narrows and the clause is genuinely unnecessary. One-liner now, still type-safe.
- **Storybook "bonus"** — noted, not counting it as covered; `apply: 'build'` already excludes the vitest/serve `test:storybook` path, and a manual `storybook build` isn't in CI.
- **`AGENTS.md` scoping prose** — added the `applyToEnvironment` client-only narrowing to the gate bullet (it was only in the code comment/docblock before).
- **`scripts/` format gap** — agreed, pre-existing and out of scope; noted that this PR does grow the ungated set.

Thanks for the three passes — the transitive-dep remedy and the `.bak`-over-`git checkout` fix in particular are real improvements I'd have shipped without.

`npm run ci` is green locally. Will re-request review once CI clears on `f4db356a`.

**Comment by cliffhall** [comment]
@claude review

**Comment by cliffhall** [comment]
Round-4 addressed in `d34cdddb` — took the three findings plus the SIGTERM nit.

**1. `status === 0` message named the wrong cause — fixed.** Split it into three diagnoses keyed off the captured output, so it points at the right file:
- output contains the known phrase → **the plugin isn't applying** (removed from `plugins`, `applyToEnvironment` no longer matching the browser env name, or an `onwarn` suppression) — pointing at `vite.config.ts`, not the constant.
- output has `node:fs` but not the phrase → **phrasing drift** → update `BROWSER_EXTERNALIZED_BUILTIN_PHRASE`.
- neither → **probe never reached the graph** (entry moved / tree-shaken).

Added a `KNOWN_PHRASE` literal for the check (kept as a literal with a pointer comment, like `smoke-web.mjs` does for `TOKEN_GLOBAL`, since this `.mjs` can't import the TS source), and added `applyToEnvironment` to the docblock's config-regression list. Good call that this is the same "a failure that misdiagnoses itself sends someone at the wrong file" class as the round-2 `result.error` fix.

**2. No spawn timeout — fixed.** Added `timeout: 10 * 60_000` + `killSignal: "SIGKILL"`. A hang now sets `result.error` (ETIMEDOUT) and reports through the existing branch with a bounded failure, instead of burning to the job's 360-min default with an empty log. Noted in the comment that `spawnSync` surfaces the timeout via `result.error`.

**3. Unguarded probe write — fixed.** Moved the probe write out of the restore-`finally` and guarded it: a read-only/EACCES checkout now fails through `fail()` with an actionable message before any mutation, matching the guarded read above it (and there's nothing to restore since nothing was written).

**Nits:**
- **SIGTERM exit code** — now 143 (SIGINT stays 130); `128 + signo`.
- **`browserExternalizedBuiltinError([])`** — left as-is: unreachable through the gate (`size > 0` guards it), and adding an empty-input guard to an internally-only-non-empty caller is dead code. Noted rather than fixed.
- **Gate tests run under `coverage`, not `validate`** — left in `src/test/integration/server/` to match the seven sibling `server/*.test.ts`; you called this "convention wins," and I'd rather not special-case one pure module out of that folder. Worth knowing `validate` won't catch a gate-logic regression, but `coverage` (and CI) do.

Thanks again for the four rounds — the three-way diagnosis and the timeout are genuine robustness wins.

`npm run ci` is green locally (including the new diagnostic paths). Will re-request review once CI clears on `d34cdddb`.

**Comment by cliffhall** [comment]
@claude review

**Comment by cliffhall** [comment]
Round-5 addressed in `371472f3` — took all three findings plus the dist nit.

**1. `KNOWN_PHRASE` drifting from the source constant — fixed with a self-check.** Added a drift guard that reads the gate module and asserts it still contains the mirrored `KNOWN_PHRASE` literal, failing fast if not. You're right this is a different risk class than the `smoke-web.mjs` token mirror (there a drift fails loudly; here it would make the *diagnosis lie*). Now a phrasing update that forgets to re-sync the script fails immediately with "the mirrored literals drifted; re-sync" rather than silently misdirecting a later plugin-unwiring to the wrong file.

**2. Failed restore escaping the `finally` and skipping the `.bak` — fixed.** `restoreEntry` now catches its own write failure and routes to a shared `saveBackupAndFail` helper (also used by the post-build content-mismatch check), so an EACCES/read-only/disk-full restore writes the sidecar `.bak` and fails actionably instead of throwing a raw stack out of the `finally` and leaving the probe injected — exactly the worst-case those lines exist to prevent.

**3. `buildStart`-reset cause missing from the diagnosis — added.** The "plugin isn't applying" branch now lists a fourth cause: a future Vite emitting the externalization warning before the client environment's `buildStart` reset runs (which would then clear it) — byte-identical symptom to the other three, and the only place a reader looks.

**Nits:**
- **Probe build left in `dist`** — added a single `console.error` note on the failing-check path (covering all three branches without repeating it) so a local debugger doesn't `npm run web` a probe bundle unaware. The expected path is unaffected (throw is in `buildEnd`, before output).
- **`original` possibly-undefined after a non-exiting `fail()`** / **any-log-level match** / **gate tests only under `coverage`** — noted, no change: `fail()` is `noreturn` (just not expressible in `.mjs`), matching at any level is deliberate robustness, and the test location follows the `server/*` convention you endorsed.

Really appreciate the five passes — the drift guard in particular turns a "keep these in sync by hand" comment into something enforced.

`npm run ci` is green locally. Will re-request review once CI clears on `371472f3`.

**Comment by cliffhall** [comment]
@claude review

**Comment by cliffhall** [comment]
Round-6 addressed in `223ec0fa` — took all three findings plus the ordering-comment nit.

**1. `#1769` too weak a success key — fixed.** Now asserts on the distinctive thrown-error prefix `Build failed (#1769)` (which `browserExternalizedBuiltinError` leads with), not a bare `#1769`. You're right this is the one direction the script must never get wrong — a false *pass* hiding a dead gate — and the bare number appears in `vite.config.ts` comments, so a code frame from an unrelated error there could have masked it. Added a comment noting this prefix + `KNOWN_PHRASE` are the script's contract with the gate module.

**2. Drift guard checked the file, not the constant — fixed.** Anchored it on the `BROWSER_EXTERNALIZED_BUILTIN_PHRASE = "…"` assignment via regex (with a small `escapeRegExp`), so the old wording lingering in the surrounding comment paragraph can't mask a changed constant — which was exactly the plausible edit that would have defeated the whole-file match. Also guarded the gate module's `readFileSync` so a moved/renamed file fails through `fail()` instead of a raw ENOENT stack, matching the entry read. Verified the regex matches the current constant and rejects a stale value.

**3. Probe module duplicated — fixed.** Extracted `PROBE_MODULE = "node:fs"` and derived both the `PROBE` string and the branch-(b) `output.includes(...)` check + its messages from it, so changing the probe module can't silently misroute a phrasing-drift failure into "probe never reached the graph."

**Nits:**
- **Diagnosis order** — added the "don't reorder these" comment (phrase before module-name, since a phrase match implies the probe reached the graph).
- **`dist` note channel/placement** — unchanged, you confirmed it's right.
- **`scripts/` not format-gated** — agreed this has grown enough to deserve its own fix; I filed a follow-up issue for closing the `server/` + `scripts/` + `vite.config.ts` prettier/eslint gap (it's the same class you flagged in rounds 2–3), rather than expand this PR's scope. [link in a follow-up comment]

Six passes in and the findings have converged on "make the script's literal contracts self-enforcing," which they now are. Thanks for the thoroughness.

`npm run ci` is green locally. Will re-request review once CI clears on `223ec0fa`.

**Comment by cliffhall** [comment]
Follow-up issue for the `scripts/` + `server/` + `vite.config.ts` prettier-gate gap: #1778 (labeled v2, on the board as Todo). Kept out of this PR to avoid scope creep.

**Comment by cliffhall** [comment]
@claude review

**Comment by cliffhall** [comment]
Round-7 addressed in `d01fe18d` — took finding #1 and all three nits.

**1. Second mirrored literal now drift-guarded too.** Extracted `ERROR_PREFIX = "Build failed (#1769)"` and added it to the drift guard against the gate module (right beside the `KNOWN_PHRASE` check, reusing the `gateSource` already read), and use it as the success key. You're right it was the last unguarded literal in the script's own stated contract — a reworded gate error would've made a correctly-firing gate report "the build broke for another reason." Benign direction, but the same class the last three rounds each closed one instance of, so worth finishing.

**Nits:**
- **`.bak` sweeping into git — fixed.** `saveBackupAndFail` now writes under `os.tmpdir()` and prints the absolute path, instead of a sidecar inside `src/` that a recovery-time `git add -A` would commit. Cleaner than gitignoring — it keeps the repo untouched entirely.
- **Branch-(b) remediation — fixed.** It now says update BOTH the gate constant AND `KNOWN_PHRASE` in one pass, so following the advice doesn't immediately trip the drift guard on the next run.
- **Single-literal assumption — pinned from the other side.** Added a note next to `BROWSER_EXTERNALIZED_BUILTIN_PHRASE` that it must stay a single string literal (no concat/template) or the regex-anchored drift guard reports a false drift.
- **`browserExternalizedBuiltinError([])`** — left as-is per the round-4 call (unreachable through the gate; a guard would be dead code needing its own coverage).

Agreed the findings have converged — the script's two literal contracts with the gate module are now both self-enforcing, and I think this is the natural stopping point. Thanks for the seven passes; the gate is materially more robust for them.

`npm run ci` is green locally. Will re-request review once CI clears on `d01fe18d`.

**Comment by cliffhall** [comment]
@claude review

**Comment by cliffhall** [comment]
Round-8 addressed in `d2a16de3` — took all three findings.

**1. `saveBackupAndFail` claiming a backup it may not have written — fixed.** It now tracks whether the write succeeded and only tells the user to restore from the `.bak` in that case; otherwise it says the probe is still injected and to restore from version control. And it writes into a fresh `mkdtempSync(path.join(tmpdir(), "verify-build-gate-"))` dir instead of a fixed tmp filename, so a pre-existing or foreign-owned `/tmp/main.tsx.verify-build-gate.bak` can't make the recovery message point at someone else's content. Agreed this was the sharpest one — a misdirection that lands *during recovery* is the worst place for it.

**2. `enforce: 'pre'` on the gate plugin — added.** You're right that a later-registered plugin returning `false` from `onLog` would filter the log for the gate and make `verify-build-gate` misreport it as "the probe never reached the browser graph" (the one diagnosis pointing away from the plugin). No plugin defines `onLog` today, so it was latent, but `enforce: 'pre'` makes "the gate sees every log" structural rather than array-position-dependent — same spirit as the round-2 `applyToEnvironment`. Verified the gate still fires with it (`verify:build-gate` green, typecheck clean).

**3. Restore-verification read guarded — fixed.** Routed it through `saveBackupAndFail` too, so the entire restore path is uniformly safe; a raw throw there would previously have skipped the backup net.

**Nits:**
- **Signal-handler exit code on a failed restore** — left as-is: a failed restore *is* an error, so `saveBackupAndFail` → exit 1 overriding the 130/143 is the right precedence; the `128 + signo` comment describes the normal path.
- **Third phrase copy in the test** — it self-checks against the exported constant, so it can't drift silently; leaving it.
- **`escapeRegExp` / empty-array** — no change (both sound as noted).

That's eight rounds; the recovery path is now uniformly guarded and the `onLog` ordering is structural. I believe this is done.

`npm run ci` is green locally. Will re-request review once CI clears on `d2a16de3`.

**Comment by cliffhall** [comment]
@claude review

**Comment by cliffhall** [comment]
Round-9 addressed in `cbe2ab5b` — took finding #1.

**Success key now proves the *probe* fired the gate, not just *a* gate firing.** Added an assertion that `PROBE_MODULE` (`node:fs`) appears among the gate's embedded offender warnings after the `ERROR_PREFIX` check. You're right this was the last direction the check could report OK without proving what it claims — a repo already leaking a built-in would trip the gate on that, masking a tree-shaken probe or a stale `entryPath` (branch (c)'s failure, inverted into a pass). Unreachable inside `npm run ci` (validate's `build:web` fails first on any pre-existing leak), but the script is a documented standalone command run exactly when someone's debugging a leak — the case where it mattered.

**Nits** — all left as-is with agreement:
- **`spawnSync` synchronous throw on a bad options object** — a programmer error that should show a stack; the `finally` still restores, so the tree stays clean.
- **`enforce: 'pre'` also orders `buildEnd` first** — the intended precedence (the `if (!error)` guard already handles a build that failed before `buildEnd`), and the alternative is worse.
- **Third phrase copy in the test** — self-checks against the exported constant, can't drift silently.

Nine rounds in, every read/write on the mutation path is guarded, both mirrored literals are drift-guarded, the `onLog` ordering is structural, and the success key now proves the probe specifically. I believe this is genuinely done.

`npm run ci` is green locally.

**Comment by cliffhall** [comment]
@claude review

**Comment by cliffhall** [comment]
Round-10 addressed in `50eb49f4` — took finding #1.

**Partial probe write can no longer destroy `main.tsx` — fixed.** You're right the "before any mutation" comment was wrong: `writeFileSync`'s default `'w'` truncates at open, so a mid-write `ENOSPC`/`EIO` leaves the entry empty or half-written. The catch now calls `restoreEntry()` before `fail()`, rolling the partial write back (and falling through to the `.bak` net if the restore itself can't write) — closing the one path that could leave the tree *destroyed* rather than merely dirty. Corrected the comment to "before the build, and any partial write is rolled back."

**Nits:**
- **`enforce: 'pre'` reach** — widened the comment to note it orders the gate ahead of Vite's *core* plugins too (including the emitting `rolldown:vite-resolve`), and why that's harmless (the gate defines no resolve/load/transform, and `onLog` delivery doesn't depend on the emitter's position).
- **Signal-killed child (`status === null`, no `error`)** — left as-is; "the build broke for another reason" is accurate enough, and it's genuinely bottom-of-the-barrel.
- **`scripts/` not in the `files` allowlist** — confirmed non-issue, no change.

Ten rounds in, every read and write on the mutation path — including a truncating partial write — is now routed into the recovery net, both mirrored literals are drift-guarded, the `onLog` ordering is structural, and the success key proves the probe specifically. This is done.

`npm run ci` is green locally.

**Comment by cliffhall** [comment]
@claude review

**Comment by cliffhall** [comment]
Round-11 addressed in `ec8117f7` — took finding #1 (a regression my round-10 fix introduced, good catch).

**Rollback no longer swallows the primary write error — fixed.** You're right: `restoreEntry()` in the catch exits via `saveBackupAndFail`→`fail` on its own failure, so the "could not write the probe" diagnosis was unreachable exactly when both writes fail (read-only checkout / ENOSPC) — and on a read-only tree nothing was ever written, so pointing at a `/tmp` backup was pure misdirection. Switched to an inline rollback that doesn't exit: it attempts the restore, tracks `rolledBack`, then always reports the PRIMARY write error, appending "restore it from version control" only when the rollback didn't take. Confirmed the control flow reports the write error now, not the restore one.

**Nits:**
- **`ERROR_PREFIX` contiguity — pinned.** Added a comment next to the gate's error message saying to keep `"Build failed (#1769)"` in a single fragment, symmetric with the `BROWSER_EXTERNALIZED_BUILTIN_PHRASE` pin, since the script drift-guards on it as a substring.
- **SIGINT in the pre-write window** — same root cause, rare, and (as you said) not worth its own guard; left it.
- **`browserExternalizedBuiltinError([])`** — left per the round-4 call.

`npm run ci` is green locally.

**Comment by cliffhall** [comment]
@claude review

**Comment by cliffhall** [comment]
Round-12 addressed in `acf10c74` — took finding #1 and nit #2.

**1. Pin comment defeating its own drift guard — fixed.** Good catch, and my regression: the round-11 comment quoted `"Build failed (#1769)"` verbatim, so it appeared twice and the whole-file `includes(ERROR_PREFIX)` guard passed on the comment alone. Reworded the comment to refer to the lead without quoting it in full (the way the `BROWSER_EXTERNALIZED_BUILTIN_PHRASE` pin avoids repeating its phrase) — confirmed the literal now occurs exactly once in the file, so the guard is meaningful again.

**2. Recovery message inferring damage — made factual.** Instead of guessing from whether the rollback write succeeded, it now reads the entry back and only appends "restore from version control" when the contents actually differ from the original (read failing → assume the worst). On a read-only checkout both writes fail at open, so the file is untouched and no longer gets a spurious damage warning. Also let me drop the "may be" hedge, since it's now a fact.

**Nits #3 (TDZ closure over `original`, chained `restored = rolledBack = true`)** — left as-is: safe by call ordering, and the reasoning is in-comment. **#1778** still tracks the `scripts/` format gap.

`npm run ci` is green locally.
