### PR TITLE
fix(web): read MCP App UI resource metadata from _meta.ui

### LINKED ISSUE #2055: [v2] [Web] MCP App renderer reads UI resource metadata from _meta instead of _meta.ui
### Which version line?

v2 — current (@modelcontextprotocol/inspector@latest)

### Which client?

Web

### Inspector version

2.2.0

### Node version

v22.19.0

### Operating system

macOS, Chrome

### Transport

Streamable HTTP

### MCP server under inspection

Any MCP App server declaring UI resource metadata under `_meta.ui` (e.g. `_meta.ui.csp` with `connectDomains` or `_meta.ui.permissions`).

### Steps to reproduce

1. Start an MCP server that serves an MCP App UI resource declaring network permissions under `_meta.ui.csp` (e.g., `connectDomains: ["https://api.example.com"]`).
2. Launch the MCP Inspector web client and connect to the server.
3. Open the **Apps** screen and open the app.
4. The running view attempts to execute a `fetch()` request to an allowlisted domain in `connectDomains`.

### Expected behavior

Per the MCP Apps specification ([`apps.mdx`](https://github.com/modelcontextprotocol/ext-apps/blob/main/specification/2026-01-26/apps.mdx#content-security-policy-enforcement) and [`spec.types.ts`](https://github.com/modelcontextprotocol/ext-apps/blob/10195ad91851502134930e9b80ec2c04e277a720/src/spec.types.ts#L694)), the host reads `_meta.ui.csp` and `_meta.ui.permissions` from the UI resource content block (or result level), parses `connectDomains`, and applies them to the generated CSP `<meta>` header in the inner iframe.

### Actual behavior

In `clients/web/src/components/elements/AppRenderer/createAppBridgeFactory.ts`, `extractHtmlAndMeta` reads `content._meta` directly as `McpUiResourceMeta`:
```typescript
meta: content._meta as McpUiResourceMeta | undefined,
```
Because the spec defines the metadata under `_meta.ui`, `meta.csp` and `meta.permissions` evaluate to `undefined`. `approveCspSources(undefined)` produces `{}` and `buildSandboxCspPolicy` generates `connect-src 'none'`, blocking outgoing network requests.

### Already prototyped a fix?

**Prompt to reproduce:**
> In `clients/web/src/components/elements/AppRenderer/createAppBridgeFactory.ts`, update `extractHtmlAndMeta` to extract UI resource metadata from `content._meta?.ui` (falling back to `result._meta?.ui`), rather than casting `content._meta` directly. Update the `uiResource` test fixture helper in `createAppBridgeFactory.test.ts` to wrap supplied metadata in `{ _meta: { ui: meta } }` to match the spec.

**Verified behavior:**
- `createAppBridgeFactory.ts` extracts `csp` and `permissions` from `_meta.ui`.
- `createAppBridgeFactory.test.ts` passes with the spec-compliant `{ _meta: { ui: ... } }` structure.

### PR DESCRIPTION
**Pull request by cliffhall**
Closes #2055

## Problem

`extractHtmlAndMeta` in `clients/web/src/components/elements/AppRenderer/createAppBridgeFactory.ts` read the UI resource's sandbox metadata straight off `_meta`:

```ts
meta: content._meta as McpUiResourceMeta | undefined,
```

But `McpUiResourceMeta` describes the value of **`_meta.ui`**, not `_meta` itself (`ext-apps` `spec.types.ts`; the tool side of this same file already reads `_meta.ui.resourceUri` via `getToolUiResourceUri`). So for every spec-conforming app, `meta.csp` and `meta.permissions` were `undefined` → `approveCspSources(undefined)` returned `{}` → `buildSandboxCspPolicy` emitted `connect-src 'none'`, and the app's declared `connectDomains` never reached the sandbox. Any App doing network work was unusable in the Apps tab.

## Fix

Read the metadata from **`_meta.ui`**, through a small `uiMeta()` helper that type-guards the value so a malformed bag degrades to "no hints" rather than being cast blindly.

Three carriers, consulted most-specific first:

1. the `resources/read` **content item**'s own `_meta.ui`;
2. the **read result envelope**'s — `McpUiReadResourceResult`, what a `registerAppResource` callback returns, types `_meta.ui` at that level;
3. the matching **`resources/list` entry**'s, which `McpUiAppResourceConfig` documents as the static default a host reviews at connection time, and which a read content item explicitly takes precedence over.

Whichever is found first wins outright — the levels are not merged, since a server restating only `csp` at a more specific level means that to be the whole grant, not a patch over the broader one.

The app-supplied `permissions` bag is also screened before it reaches the sandbox (`approveSandboxPermissions`, beside the existing `approveCspSources`). The proxy's `buildAllowAttribute()` tests each key for truthiness, so `{ camera: "false" }` would have read as a grant. A key now counts as requested only when its value is an **object** — the marker the spec defines is `{}`, and the object's presence is the request — and the value is normalized to `{}` on the way out, so no unrecognized field reaches the proxy. The object is deliberately *not* required to be empty: `{}` is the spec's extension point, so rejecting a populated one would drop grants from servers written against a newer spec. Everything else fails closed: `true`, `false`, any string, `null`, a number, an array, and any key outside the four the proxy knows. Nothing screened this before because, thanks to this same bug, no permissions ever reached the proxy at all.

The listing reaches the factory through a new optional dep, `getListedResourceMeta?: (uri) => object | undefined`, wired in `App.tsx` for both bridge factories from the resources list. Optional because a host with no listing — or one whose listing omits this URI, which is common for `ui://` resources — must be unaffected rather than broken.

## Tests

`createAppBridgeFactory.test.ts`'s `uiResource` fixture now builds the real wire shape (`{ _meta: { ui: … } }`), so the existing CSP/permissions assertions exercise the spec structure rather than a shape no server sends. Cases added:

- each of the three carriers is honored, and the precedence between them (content item > result envelope > listing)
- none present → still renders under `connect-src 'none'`
- an **unnested** `_meta` bag is ignored — locks the regression direction
- `sandbox-csp.test.ts` covers the permissions screen, including `{ camera: "false" }`

`App.test.tsx` adds a case for the App-level wiring itself (a pass-through spy over the factory), since the factory's own tests inject the dep and so cannot see that wiring break.

## Screenshots

None — the change has no visual surface. It alters the `Content-Security-Policy` `<meta>` generated for the sandboxed inner iframe, which is not rendered UI. The behavior is pinned by the unit tests above; the `mcp-app-http.json` showcase server already declares its metadata under `_meta.ui` (with empty `connectDomains`), so the Apps tab renders identically before and after.

## Note on #2056

Not fixed here, and not a duplicate. `_meta.ui.domain` becomes *readable* with this change, but nothing consumes it: `McpUiSandboxResourceReadyNotification.params` has no `domain` field, and the `Origin: null` in that report comes from the deliberate opaque-origin sandbox (`sandbox_proxy.html` withholds `allow-same-origin` by design, per #1565). Honoring `domain` is a sandbox-hosting design question, tracked separately.

## Verification

`npm run ci` passes.

### CODE REVIEW

File: clients/web/src/components/elements/AppRenderer/createAppBridgeFactory.ts [hunk 1]
```diff
@@ -110,7 +132,7 @@ function extractHtmlAndMeta(result: ReadResourceResult): {
     if (typeof text === "string") {
       return {
         html: text,
-        meta: content._meta as McpUiResourceMeta | undefined,
+        meta: uiMeta(content._meta) ?? uiMeta(result._meta),
```
[the remark this answers is not in the document]
Comment (cliffhall) [reply clients/web/src/components/elements/AppRenderer/createAppBridgeFactory.ts]: Good catch — you're right, and I've changed it.

I checked `McpUiAppResourceConfig` in the pinned `@modelcontextprotocol/ext-apps@1.7.5`, and it says exactly what you describe: the listing-level `_meta.ui` "is included in the `resources/list` response and serves as a static default for hosts to review at connection time. When the `resources/read` content item also includes `_meta.ui`, the content-item value takes precedence." The read *result* envelope is not a documented carrier at all — that fallback was my invention, so I've dropped it rather than documenting it as legacy compat.

**What changed (commit `82c3ac2`):**

- `extractHtmlAndMeta` now takes the matching listing entry's `_meta` and falls back to *its* `.ui`: `uiMeta(content._meta) ?? uiMeta(listedMeta)`. Content item wins outright (no merge), matching the "takes precedence" wording.
- New optional dep `getListedResourceMeta?: (uri: string) => object | undefined`. Optional because a host with no resource listing — or one whose listing doesn't include this URI, which is common for `ui://` resources — must be unaffected rather than broken.
- Wired in `App.tsx` for both bridge factories from the `resources/list` items. It reads through a ref: `resources` is derived further down the component than the factory memo, and the factories only read it inside the async `sandboxready` handler, long after the render that produced it.

**Tests** (`createAppBridgeFactory.test.ts`): the result-level case is replaced by three — the listing-level fallback is honored (and `getListedResourceMeta` is called with the resource URI), a content item's `_meta.ui` beats the listing's outright, and no metadata at either level still renders under `connect-src 'none'`.

`npm run ci` passes.

**Comment by cliffhall** [comment]
## Copilot review round 1 — response

(Mirrored at PR level; the inline thread goes outdated once the fix is pushed.)

Good catch — you're right, and I've changed it.

I checked `McpUiAppResourceConfig` in the pinned `@modelcontextprotocol/ext-apps@1.7.5`, and it says exactly what you describe: the listing-level `_meta.ui` "is included in the `resources/list` response and serves as a static default for hosts to review at connection time. When the `resources/read` content item also includes `_meta.ui`, the content-item value takes precedence." The read *result* envelope is not a documented carrier at all — that fallback was my invention, so I've dropped it rather than documenting it as legacy compat.

**What changed (commit `82c3ac2`):**

- `extractHtmlAndMeta` now takes the matching listing entry's `_meta` and falls back to *its* `.ui`: `uiMeta(content._meta) ?? uiMeta(listedMeta)`. Content item wins outright (no merge), matching the "takes precedence" wording.
- New optional dep `getListedResourceMeta?: (uri: string) => object | undefined`. Optional because a host with no resource listing — or one whose listing doesn't include this URI, which is common for `ui://` resources — must be unaffected rather than broken.
- Wired in `App.tsx` for both bridge factories from the `resources/list` items. It reads through a ref: `resources` is derived further down the component than the factory memo, and the factories only read it inside the async `sandboxready` handler, long after the render that produced it.

**Tests** (`createAppBridgeFactory.test.ts`): the result-level case is replaced by three — the listing-level fallback is honored (and `getListedResourceMeta` is called with the resource URI), a content item's `_meta.ui` beats the listing's outright, and no metadata at either level still renders under `connect-src 'none'`.

`npm run ci` passes.

File: clients/web/src/components/elements/AppRenderer/createAppBridgeFactory.ts [hunk 2]
```diff
@@ -100,8 +109,37 @@ export interface AppBridgeFactoryDeps {
...
+}
+
+/**
+ * First text content block of a UI resource, plus its `_meta.ui` sandbox hints.
+ *
+ * `listedMeta` is the `_meta` of the matching `resources/list` entry, which
+ * ext-apps documents as the static default a host can review at connection
+ * time; a `resources/read` content item carrying its own `_meta.ui` takes
+ * precedence over it (`McpUiAppResourceConfig`). Nothing else is consulted —
+ * in particular the read RESULT's own `_meta` is not a documented carrier.
```
[the remark this answers is not in the document]
Comment (cliffhall) [reply clients/web/src/components/elements/AppRenderer/createAppBridgeFactory.ts]: Fixed — the PR description now describes the final contract: content item's `_meta.ui` wins, the `resources/list` entry's `_meta.ui` is the fallback, and the read result envelope is explicitly called out as not a documented carrier (with a note that an earlier revision of this PR used it).

File: clients/web/src/App.tsx [hunk 3]
```diff
@@ -784,10 +785,24 @@ function App() {
...
+    (uri: string) =>
+      listedResourcesRef.current.find((r) => r.uri === uri)?._meta,
+    [],
+  );
+
   const sandboxBridgeFactory = useMemo(
     () =>
       createAppBridgeFactory({
         getClient: () => inspectorClient?.getAppRendererClient() ?? null,
+        getListedResourceMeta,
```
[the remark this answers is not in the document]
Comment (cliffhall) [reply clients/web/src/App.tsx:815]: Agreed — added in `a1c00e51`.

`App.test.tsx` now carries a pass-through mock of `createAppBridgeFactory` that records the deps App hands it (it still calls the real factory, so nothing else in that file changes behavior), plus a test that:

- mocks `useManagedResources` to return a listed resource with `_meta.ui.csp.connectDomains`,
- renders `App`, and
- asserts **every** factory App builds — the Apps-tab one and the elicitation one — receives a `getListedResourceMeta` that resolves that URI to the listing `_meta` and returns `undefined` for an unknown URI.

That's the gap you identified: the bridge-factory tests inject the dep, so a regression in the App wiring would have left the fallback dead with all of them still green. The `useManagedResources` mock is module-level and shared, so the test restores the empty-list default in an `afterEach` rather than leaving a populated list for whatever runs next.

`npm run ci` passes (all 77 `App.test.tsx` cases included, and `smoke:web:app` still drives connect → open app → `data-app-status="ready"`).

**Comment by cliffhall** [comment]
## Copilot review round 2 — response

(Mirrored at PR level; inline threads go outdated once the fix is pushed.)

**1. Stale PR description.** Fixed — the PR description now describes the final contract: content item's `_meta.ui` wins, the `resources/list` entry's `_meta.ui` is the fallback, and the read result envelope is explicitly called out as not a documented carrier (with a note that an earlier revision of this PR used it).

**2. App-level wiring untested.** Agreed — added in `a1c00e51`.

`App.test.tsx` now carries a pass-through mock of `createAppBridgeFactory` that records the deps App hands it (it still calls the real factory, so nothing else in that file changes behavior), plus a test that:

- mocks `useManagedResources` to return a listed resource with `_meta.ui.csp.connectDomains`,
- renders `App`, and
- asserts **every** factory App builds — the Apps-tab one and the elicitation one — receives a `getListedResourceMeta` that resolves that URI to the listing `_meta` and returns `undefined` for an unknown URI.

That's the gap you identified: the bridge-factory tests inject the dep, so a regression in the App wiring would have left the fallback dead with all of them still green. The `useManagedResources` mock is module-level and shared, so the test restores the empty-list default in an `afterEach` rather than leaving a populated list for whatever runs next.

`npm run ci` passes (all 77 `App.test.tsx` cases included, and `smoke:web:app` still drives connect → open app → `data-app-status="ready"`).

File: clients/web/src/App.test.tsx [hunk 4]
```diff
@@ -3117,3 +3142,48 @@ describe("App background command rejections (#2049)", () => {
...
+  });
+
+  afterEach(() => {
+    // The hook mock is module-level and shared, so put the empty-list default
+    // back rather than leaving a populated list for whatever runs next.
+    vi.mocked(useManagedResources).mockReturnValue({
+      resources: [],
+      refresh: vi.fn(),
+      clearListChanged: vi.fn(),
+    } as unknown as ReturnType<typeof useManagedResources>);
```
[the remark this answers is not in the document]
Comment (cliffhall) [reply clients/web/src/App.test.tsx]: Agreed on both occurrences (the suppressed one on the `afterEach` restore as well) — fixed in `9f8dc82a`.

Both casts are gone. A `managedResourcesResult(resources: Resource[]): UseManagedResourcesResult` helper now builds the complete shape — `error: null`, `resources`, `listChanged: false`, `refresh`, `clearListChanged` — and both call sites (the populated list under test and the empty-list restore) go through it with no cast at all. So the mock is checked against the hook's real contract, and adding a field to `UseManagedResourcesResult` now fails the typecheck here instead of silently passing.

`npm run ci` passes.

**Comment by cliffhall** [comment]
## Copilot review round 3 — response

(Mirrored at PR level; inline threads go outdated once the fix is pushed. This round also carried one **suppressed** comment, on line 3174 — the same double cast in the `afterEach` restore — which is fixed by the same change.)

Agreed on both occurrences (the suppressed one on the `afterEach` restore as well) — fixed in `9f8dc82a`.

Both casts are gone. A `managedResourcesResult(resources: Resource[]): UseManagedResourcesResult` helper now builds the complete shape — `error: null`, `resources`, `listChanged: false`, `refresh`, `clearListChanged` — and both call sites (the populated list under test and the empty-list restore) go through it with no cast at all. So the mock is checked against the hook's real contract, and adding a field to `UseManagedResourcesResult` now fails the typecheck here instead of silently passing.

`npm run ci` passes.

File: clients/web/src/components/elements/AppRenderer/createAppBridgeFactory.ts [hunk 5]
```diff
@@ -100,8 +109,37 @@ export interface AppBridgeFactoryDeps {
...
+ * side, where `getToolUiResourceUri` already reads `_meta.ui.resourceUri`.
+ */
+function uiMeta(meta: object | undefined): McpUiResourceMeta | undefined {
+  // `_meta` is typed with an index signature, which has no properties in common
+  // with a `{ ui?: unknown }` parameter — hence the cast rather than a narrower
+  // parameter type. Reading one key off an untyped bag is safe.
+  const ui = (meta as { ui?: unknown } | undefined)?.ui;
+  return ui !== null && typeof ui === "object"
+    ? (ui as McpUiResourceMeta)
+    : undefined;
```
[the remark this answers is not in the document]
Comment (cliffhall) [reply clients/web/src/components/elements/AppRenderer/createAppBridgeFactory.ts]: Good find — you're right that this PR is what makes the permissions path live at all (before it, `meta.permissions` was always `undefined`, so nothing ever reached `buildAllowAttribute`). Fixed in `45785a0a`.

I verified the mechanism you describe: `sandbox_proxy.html`'s `buildAllowAttribute()` tests `permissions["camera"]` and friends for plain truthiness, so `{ camera: "false" }` — a plausible way for a server to mean "off" — would indeed have switched the `allow` token on.

**`approveSandboxPermissions`** now sits next to `approveCspSources` in `utils/sandbox-csp.ts`, and the factory sends/echoes its result rather than the raw bag:

- keeps only the four keys the proxy knows (same `exhaustive*Keys` compile-time completeness trick as `CSP_KEYS`, so a new upstream key can't be silently dropped);
- accepts a key only when the value is the spec's empty-object marker (`camera: {}`) or `true` as the obvious shorthand — and normalizes it to `{}`;
- drops everything else: `"false"`, `1`, `null`, any string, plus unknown keys — warning on a malformed value, silently on an explicit `false`, which is a refusal rather than a mistake;
- returns `undefined` when nothing survives, so both the notification and `hostCapabilities.sandbox` carry no permissions at all rather than an empty object.

Four cases added in `sandbox-csp.test.ts`, including your exact `{ camera: "false" }` example. I left the `csp` side alone — `approveCspSources` already validates key-by-key with an array check and a per-entry regex.

**On the suppressed pagination comment** (`App.tsx:1257`) — the analysis is right, and I've documented it rather than closed it. Under `paginatedLists` the ref sees only the pages fetched so far, so an app whose listing entry is on a later page gets no hints and falls back to `connect-src 'none'`. I don't think an eager cursor walk is the right trade: the listing is a documented *default* that a read content item overrides, the outcome in that case is exactly the pre-PR behavior rather than a regression, and walking the list would issue precisely the requests the user opted out of by turning pagination on. There's a comment at that line stating the limit and the reasoning, so it's a known bound rather than an oversight.

`npm run ci` passes, `smoke:web:app` included (connect → open app → `data-app-status="ready"`).

**Comment by cliffhall** [comment]
## Copilot review round 4 — response

(Mirrored at PR level; inline threads go outdated once the fix is pushed. Covers the visible comment and the **suppressed** one on `App.tsx:1257`.)

Good find — you're right that this PR is what makes the permissions path live at all (before it, `meta.permissions` was always `undefined`, so nothing ever reached `buildAllowAttribute`). Fixed in `45785a0a`.

I verified the mechanism you describe: `sandbox_proxy.html`'s `buildAllowAttribute()` tests `permissions["camera"]` and friends for plain truthiness, so `{ camera: "false" }` — a plausible way for a server to mean "off" — would indeed have switched the `allow` token on.

**`approveSandboxPermissions`** now sits next to `approveCspSources` in `utils/sandbox-csp.ts`, and the factory sends/echoes its result rather than the raw bag:

- keeps only the four keys the proxy knows (same `exhaustive*Keys` compile-time completeness trick as `CSP_KEYS`, so a new upstream key can't be silently dropped);
- accepts a key only when the value is the spec's empty-object marker (`camera: {}`) or `true` as the obvious shorthand — and normalizes it to `{}`;
- drops everything else: `"false"`, `1`, `null`, any string, plus unknown keys — warning on a malformed value, silently on an explicit `false`, which is a refusal rather than a mistake;
- returns `undefined` when nothing survives, so both the notification and `hostCapabilities.sandbox` carry no permissions at all rather than an empty object.

Four cases added in `sandbox-csp.test.ts`, including your exact `{ camera: "false" }` example. I left the `csp` side alone — `approveCspSources` already validates key-by-key with an array check and a per-entry regex.

**On the suppressed pagination comment** (`App.tsx:1257`) — the analysis is right, and I've documented it rather than closed it. Under `paginatedLists` the ref sees only the pages fetched so far, so an app whose listing entry is on a later page gets no hints and falls back to `connect-src 'none'`. I don't think an eager cursor walk is the right trade: the listing is a documented *default* that a read content item overrides, the outcome in that case is exactly the pre-PR behavior rather than a regression, and walking the list would issue precisely the requests the user opted out of by turning pagination on. There's a comment at that line stating the limit and the reasoning, so it's a known bound rather than an oversight.

`npm run ci` passes, `smoke:web:app` included (connect → open app → `data-app-status="ready"`).

File: clients/web/src/utils/sandbox-csp.ts [hunk 6]
```diff
@@ -75,6 +78,65 @@ export function approveCspSources(
...
+ * obvious shorthand; everything else — `false`, any string, `null`, a number —
+ * is dropped, as is any key outside the four the proxy knows.
+ *
+ * Returns undefined when nothing survives, so the notification and the
+ * `hostCapabilities.sandbox` echo carry no permissions at all rather than an
+ * empty object.
+ */
+export function approveSandboxPermissions(
+  permissions: McpUiResourcePermissions | undefined,
+): McpUiResourcePermissions | undefined {
```
[the remark this answers is not in the document]
Comment (cliffhall) [reply clients/web/src/utils/sandbox-csp.ts:131]: Both taken — `286dd86f`.

**Parameter type.** You're right that it was claiming a validated shape at the exact point that decides the shape. `approveSandboxPermissions(permissions: unknown)` now rejects a non-object outright, copies the bag into a `Record<string, unknown>`, and narrows per key while reading. Every malformed fixture in the tests is passed as a plain object literal — no casts left in that describe block.

**The `true` shorthand (suppressed comment).** Agreed, and dropped. The spec defines each permission as an object (`clipboardWrite?: {}`), so `true` was me guessing — and guessing in the *granting* direction is the wrong bet for untrusted input: a server typo would have switched an iframe permission on. Only the empty-object marker grants now. Arrays are rejected too (`typeof [] === "object"` would otherwise have slipped through), and the doc comment states the rule and why. The shorthand test is replaced: `microphone: true` now sits in the "drops a truthy non-marker" case alongside `"false"`, `1`, and `[]`, all four warning and yielding `undefined`.

One deliberate non-change: `approveCspSources` keeps its `McpUiResourceCsp | undefined` parameter, and its pre-existing test still casts one fixture. Same argument would apply, but that function and its tests are untouched by this PR and #2055 is a metadata-path fix — worth doing, not worth widening this diff for.

`npm run ci` passes.

**Comment by cliffhall** [comment]
## Copilot review round 5 — response

(Mirrored at PR level; inline threads go outdated once the fix is pushed. Covers the visible comment and the **suppressed** one on `sandbox-csp.ts:126`.)

Both taken — `286dd86f`.

**Parameter type.** You're right that it was claiming a validated shape at the exact point that decides the shape. `approveSandboxPermissions(permissions: unknown)` now rejects a non-object outright, copies the bag into a `Record<string, unknown>`, and narrows per key while reading. Every malformed fixture in the tests is passed as a plain object literal — no casts left in that describe block.

**The `true` shorthand (suppressed comment).** Agreed, and dropped. The spec defines each permission as an object (`clipboardWrite?: {}`), so `true` was me guessing — and guessing in the *granting* direction is the wrong bet for untrusted input: a server typo would have switched an iframe permission on. Only the empty-object marker grants now. Arrays are rejected too (`typeof [] === "object"` would otherwise have slipped through), and the doc comment states the rule and why. The shorthand test is replaced: `microphone: true` now sits in the "drops a truthy non-marker" case alongside `"false"`, `1`, and `[]`, all four warning and yielding `undefined`.

One deliberate non-change: `approveCspSources` keeps its `McpUiResourceCsp | undefined` parameter, and its pre-existing test still casts one fixture. Same argument would apply, but that function and its tests are untouched by this PR and #2055 is a metadata-path fix — worth doing, not worth widening this diff for.

`npm run ci` passes.

**Comment by cliffhall** [comment]
## Copilot review round 6 — response

(No visible comments this round; both items were in the **Suppressed comments** block.)

No new visible comments this round, but both **suppressed** ones were right and are fixed in `e2a88d49`.

**1. The read result envelope IS a documented carrier** (`createAppBridgeFactory.ts:152`). I checked, and you're correct: `McpUiReadResourceResult` in the pinned `ext-apps@1.7.5` is `ReadResourceResult & { _meta?: { ui?: McpUiResourceMeta } }`, and `McpUiReadResourceCallback` — what `registerAppResource` takes — returns exactly that. So a server stamping the envelope is using a supported shape, and dropping it lost their CSP/permissions.

This means round 1's guidance was half right: the *listing* fallback was genuinely missing, but "the result envelope is not a carrier" was wrong, and I removed a working path on it. Restored, and all three are now consulted most-specific first — content item → result envelope → listing entry — with the first found winning outright rather than the levels merging (a server restating only `csp` at a more specific level means that to be the whole grant, not a patch over the broader one). Two tests back: the envelope carrier is honored, and it beats the listing. The precedence chain is documented on `extractHtmlAndMeta` and in the PR description.

**2. The App wiring test proved less than it claimed** (`App.test.tsx:3186`). Also right — `appBridgeFactoryDeps.length > 0` was satisfied by whichever factory was constructed first, so stripping the dep from one call site would have left the other's deps in the array and the loop would still have passed. It now waits for **both** by their `advertiseElicitation` flag (`find(d => !d.advertiseElicitation)` and `find(d => d.advertiseElicitation === true)`) and asserts the lookup on each specifically, so removing the wiring from either call site fails the test.

`npm run ci` passes.

File: clients/web/src/utils/sandbox-csp.ts [hunk 7]
```diff
@@ -75,6 +78,73 @@ export function approveCspSources(
...
+  const approved: McpUiResourcePermissions = {};
+  let granted = false;
+  for (const key of PERMISSION_KEYS) {
+    const requested = bag[key];
+    if (requested === undefined || requested === false) continue;
+    if (
+      typeof requested === "object" &&
+      requested !== null &&
+      !Array.isArray(requested)
+    ) {
```
[the remark this answers is not in the document]
Comment (cliffhall) [reply clients/web/src/utils/sandbox-csp.ts:143]: Pushing back on this one, with the doc corrected instead.

The stated rule was too narrow — that's on me — but requiring **no own keys** would be wrong. `{}` in the MCP Apps spec is a type with no fields *yet*, not a promise there will never be any; it's the extension point. Requiring emptiness means the day a permission gains an option (`camera: { facingMode: … }`), every server written against that newer spec silently loses the grant — failing closed in a case where the key's presence unambiguously *is* the request.

What matters is that an unrecognized field can't leak: the value is normalized to `{}` on the way out, so `{ camera: { enabled: false } }` forwards as `camera: {}` and the proxy sees only the token. A field like `enabled: false` can't *narrow* a grant the key's presence already asked for — but that's true of the spec today with any shape, and inventing a narrowing rule the protocol doesn't define would be the same "guess and grant differently" mistake in the other direction.

So the check stays "an object" and the doc now says so, with the extension-point reasoning; a scalar (`true`, `"false"`, `1`), `null`, and an array remain rejected. Added your `{ camera: { enabled: false } }` case as a test pinning that it normalizes to `{ camera: {} }`. Happy to tighten if you think the narrowing case is real.

File: clients/web/src/components/elements/AppRenderer/createAppBridgeFactory.test.ts [hunk 8]
```diff
@@ -230,6 +246,182 @@ describe("createAppBridgeFactory", () => {
...
+      html: string;
+      permissions: unknown;
+    };
+    expect(call.permissions).toEqual({ microphone: {} });
+    expect(call.html).toContain("connect-src https://envelope.example.com");
+  });
+
+  it("prefers the read result's _meta.ui over the listing entry's", async () => {
+    // Precedence runs most-specific first: content item, then the result
+    // envelope, then the listing default.
```
[the remark this answers is not in the document]
Comment (cliffhall) [reply clients/web/src/components/elements/AppRenderer/createAppBridgeFactory.test.ts:282]: Right — none of the added cases would have caught the first two operands being swapped, since each supplied only one fallback level. Fixed in `53943c2e`.

New case carries **all three** carriers at once — content item `https://content.example.com`, result envelope `https://envelope.example.com`, listing `https://listed.example.com` — and asserts the generated CSP contains the content item's and neither of the others. That pins the full order rather than two independent pairs.

**Comment by cliffhall** [comment]
## Copilot review round 7 — response

Two visible comments and one **suppressed**; two taken, one pushed back on.

### 1. Precedence not fully pinned (`createAppBridgeFactory.test.ts:282`)

Right — none of the added cases would have caught the first two operands being swapped, since each supplied only one fallback level. Fixed in `53943c2e`.

New case carries **all three** carriers at once — content item `https://content.example.com`, result envelope `https://envelope.example.com`, listing `https://listed.example.com` — and asserts the generated CSP contains the content item's and neither of the others. That pins the full order rather than two independent pairs.

### 2. Malformed `_meta.ui` fell through (suppressed, `createAppBridgeFactory.ts:128`)

Correct, and fixed in `53943c2e`. `uiMeta` returned `undefined` for both "this bag declares no `ui`" and "its `ui` is unusable", so the `??` chain treated a malformed higher-priority carrier as silent and fell through — granting whatever a *broader* carrier asked for. Wrong precedence and the wrong direction to fail in, exactly as you say.

It now returns `{ meta } | undefined`, which separates the two: no `ui` key → `undefined` (this carrier is silent, keep looking); a declared but malformed `ui` (`null`, a scalar, an array) → `{ meta: undefined }` (this carrier spoke, and what it said is unusable — stop). `extractHtmlAndMeta` reads the first non-`undefined` entry and uses its `.meta`.

Regression case added: a content item declaring `ui: null` alongside a listing entry granting camera and a `connectDomains` — result is no permissions and `connect-src 'none'`, with the listing's domain absent.

### 3. Non-empty permission object (`sandbox-csp.ts:135`) — pushed back

Pushing back on this one, with the doc corrected instead.

The stated rule was too narrow — that's on me — but requiring **no own keys** would be wrong. `{}` in the MCP Apps spec is a type with no fields *yet*, not a promise there will never be any; it's the extension point. Requiring emptiness means the day a permission gains an option (`camera: { facingMode: … }`), every server written against that newer spec silently loses the grant — failing closed in a case where the key's presence unambiguously *is* the request.

What matters is that an unrecognized field can't leak: the value is normalized to `{}` on the way out, so `{ camera: { enabled: false } }` forwards as `camera: {}` and the proxy sees only the token. A field like `enabled: false` can't *narrow* a grant the key's presence already asked for — but that's true of the spec today with any shape, and inventing a narrowing rule the protocol doesn't define would be the same "guess and grant differently" mistake in the other direction.

So the check stays "an object" and the doc now says so, with the extension-point reasoning; a scalar (`true`, `"false"`, `1`), `null`, and an array remain rejected. Added your `{ camera: { enabled: false } }` case as a test pinning that it normalizes to `{ camera: {} }`. Happy to tighten if you think the narrowing case is real.

`npm run ci` passes.

**Comment by cliffhall** [comment]
## Copilot review round 8 — response

No new visible comments; one **suppressed** item, which I've documented rather than fixed — `acf9ff94`.

The race is real: `ManagedResourcesState` fetches `resources/list` asynchronously on connect, and a deep-linked `autoOpen` can reach `sandboxready` before it lands, so the lookup returns nothing for an app whose hints exist only in the listing.

I'm not making the lookup wait on list readiness, because the failure mode of doing so is worse than the one it fixes:

- **The wait may never end.** A server advertising no `resources` capability never issues that request at all, and one whose list errors resolves to a failure with no retry. Gating the sandbox on it turns "this app is missing an optional default" into "this app never renders" — for every app on those servers, not just listing-only ones.
- **The bad outcome here equals the pre-PR outcome.** Losing the race yields no hints and `connect-src 'none'`, which is exactly what every app got before this PR. It's a default not applied, not a regression.
- **The carrier is a default by design.** ext-apps calls the listing value the "static default", explicitly overridden by the read content item — the two carriers this PR consults *first*, both of which arrive with the very `resources/read` that opens the app and so cannot race it. A server that needs its CSP honored deterministically has an unraced place to put it, and the showcase servers do exactly that.

So the lookup now says at the point of use that it is best-effort, that "no entry" and "not loaded yet" are deliberately not distinguished, and why blocking is the worse trade. Happy to revisit if a readiness signal that can't hang (capability-aware, error- and timeout-terminated) is worth building — but that's a bigger change than #2055, and I'd rather it be its own issue than ride in on a metadata-path fix.

`npm run ci` passes.

**Comment by cliffhall** [comment]
## Copilot review round 9 — response

No visible comments; one **suppressed** item, on the PR description overstating the permission check.

Right — the description hadn't caught up with the round-7 change. Fixed.

It now says a key counts as requested when its value is an **object** (the spec's marker is `{}`, and the object's presence is the request), that the value is normalized to `{}` on the way out so no unrecognized field reaches the proxy, and that the object is deliberately not required to be empty because `{}` is the spec's extension point — rejecting a populated one would drop grants from servers written against a newer spec. The fail-closed list is spelled out explicitly: `true`, `false`, any string, `null`, a number, an array, and any key outside the four the proxy knows.

Description-only change; no code moved, so the last `npm run ci` run still stands.

**Comment by cliffhall** [comment]
## Heads-up: this PR now also carries a one-line fix for a `v2/main` breakage

`v2/main` has been failing `tsc -b` since `8b9839cc` (2026-08-24 00:48), from a **semantic merge conflict** between two PRs that were each green on their own:

- **#2094** retyped `RequestMetadata` as `Record<string, StrictJsonValue>` (`core/mcp/types.ts:393`)
- **#2087**, merged three minutes later, added an `updateServerSettings` case passing `metadata: []` (`clients/web/src/test/core/react/useServers.test.tsx:1310`)

Neither touched the other's lines, so both merged cleanly and nothing caught it until the two were in one tree:

```
src/test/core/react/useServers.test.tsx(1310,11): error TS2322:
  Type 'never[]' is not assignable to type 'RequestMetadata'.
  Index signature for type 'string' is missing in type 'never[]'.
```

This branch merged `v2/main` and inherited the break, so its CI could not pass without the repair. One occurrence repo-wide, `[]` → `{}` (`ab92bab5`).

It's unrelated to #2055 and would normally be its own issue and PR — noting it here so the extra file in the diff is accounted for, and so whoever reviews knows `v2/main` was already red before this branch touched it.

`npm run ci` passes locally end to end.
