### PR TITLE
fix: load @napi-rs/keyring lazily so an unsupported platform degrades instead of crashing (#1905)

### LINKED ISSUE #1848: KeyringSecretStore throws from the AsyncEntry constructor, defeating its own degradation contract (500 on GET /api/servers)
**Version:** v2 (`main`)
**Affected client:** core (observed via Web; CLI/TUI catalog loads hit the same path)

Follow-up to #1845 with a root cause and prompt to fix. Happy to fold this into that issue instead if you'd prefer it tracked there.

## Prompt

I fixed this locally with the following prompt:

---

In `core/auth/node/secret-store.ts`, `KeyringSecretStore` constructs its `AsyncEntry` outside the `try` in `get`, `set` and `delete`. The `@napi-rs/keyring` constructor performs the platform-store setup and throws when no keychain is reachable, so the documented degradation contract (`:79-89`) never engages: the raw error escapes instead, 500ing every `GET /api/servers` and breaking CLI/TUI catalog loads on any box without a Secret Service.

Move the construction inside the existing `try` blocks in all three methods so the documented contract holds when the failure is at construction time: `get` returns `null`, `delete` silently no-ops, and `set` is the only operation that throws — as `KeychainUnavailableError`, so the routes' 503 translation and the `migratePlaintextSecrets` skip branch in `core/mcp/remote/node/server.ts` both engage. Update the doc comment if the wording no longer matches.

Extend the `vi.mock` in `clients/web/src/test/integration/auth/node/secret-store.test.ts`: its stub constructor cannot fail today, which is why this gap survived the coverage gate. Add a `constructorThrows` hook alongside the existing method-level `failures` flags and cover all three methods under it.

---

## Detail

`AsyncEntry::new` in `@napi-rs/keyring` does the platform-store setup (on Linux, the Secret Service connect with a keyutils fallback) and returns a `Result` — so it throws when neither backend is reachable. Because construction sits outside the `try` in `get`/`set`/`delete`, the documented behavior at `secret-store.ts:79-89` ("`get` returns `null`, destructive ops no-op, only `set` hard-fails") never engages for a construction-time failure.

Two consequences beyond the 500 itself:

- `expectedSecretFields` always includes the OAuth slot, so `rehydrateConfig` constructs an entry for **every** server. The default seeded catalog is enough to 500 the first `GET /api/servers`, before any server is added.
- The escaping error isn't a `KeychainUnavailableError`, so it bypasses both the routes' 503 translation and the `migratePlaintextSecrets` skip branch in `core/mcp/remote/node/server.ts` — a generic 500 instead of the actionable message.

**Before:** `GET /api/servers` → 500 `Failed to read server list: Couldn't access platform storage: PermissionDenied` (note the unwrapped keyring message — proof it escaped the `try`).
**After:** 200 with the server list; secret-free entries work with no keychain present.

## Verification

Reproduced and confirmed fixed in the published container, which has no D-Bus session:

```bash
docker build -t mcp-inspector .
docker run --rm -p 6274:6274 mcp-inspector
```

Before the change, adding a server appeared to succeed (`POST` → `{"ok":true}`) but the list never loaded; after, the round-trip works.

## Judgment call worth flagging

Having `set` wrap a **constructor** failure as `KeychainUnavailableError` changes what callers see from a raw throw to a typed one. That's what makes the 503 ton-skip branch fire, and it matches the documented contract — but it is a behavior change for anything matching on the raw error, so it's worth a deliberate decision rather than being assumed.

## Related, separate question

This restores non-secret flows in a container but doesn't answer what secret persistence should *mean* there. Since `SecretStore` is already an interface (with `InMemorySecretStore` alongside), an explicit file-backed or in-memory store may be a better container story than shipping a keyring daemon. Happy to open that separately if useful.

### LINKED ISSUE #1852: Unable to run the web UI on Windows
**Describe the bug**
After today's update I am unable to open the web UI for the MCP tester

**To Reproduce**

Just try to open the UI as documented on the wiki:

> npx @modelcontextprotocol/inspector
Error running MCP Inspector: Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.

> node --version
v25.9.0

> npm --version
11.12.1

Before today's update it was working good. Already tried multiple node versions and all of them fail.

**Expected behavior**
Should open the MCP tester web UI

**Logs**
If applicable, add logs to help explain your problem.

**Additional context**

### LINKED ISSUE #1905: Inspector v2.0.0 fails to start on Android/Termux because @napi-rs/keyring is imported unconditionally
**Describe the bug**

`@modelcontextprotocol/inspector` v2.0.0 fails to start on Android (Termux) because `@napi-rs/keyring` is imported unconditionally during module initialization.

The Inspector exits immediately before it can execute its own fallback logic for systems without an OS keychain.

---

**To Reproduce**

1. Install the latest Inspector.

```sh
mkdir tmp-inspector
cd tmp-inspector

npm init -y
npm install @modelcontextprotocol/inspector
```

2. Run:

```sh
npx @modelcontextprotocol/inspector
```

3. Observe that the Inspector exits immediately with a native binding error.

---

**Expected behavior**

The Inspector should start successfully even if an OS keychain is unavailable or unsupported.

If `@napi-rs/keyring` cannot be used on the current platform, the Inspector should gracefully fall back to a non-keyring credential store (or disable credential persistence) instead of failing during startup.

---

**Logs**

Initial error:

```text
Error running MCP Inspector: Cannot find native binding.
npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828).
Please try `npm i` again after removing both package-lock.json and node_modules directory.
```

After investigation, the underlying error is:

```text
Error: Cannot find module './keyring.android-arm64.node'
```

followed by:

```text
Error: Cannot find module '@napi-rs/keyring-android-arm64'
```

The dependency tree shows:

```text
tmp-inspector@1.0.0
└─┬ @modelcontextprotocol/inspector@2.0.0
  └── @napi-rs/keyring@1.3.0
```

No Android-specific keyring package is installed.

I also verified that this is **not** a general native module loading issue:

- `@rolldown/binding-android-arm64` loads successfully.
- The Android native `.node` file is present and can be required without errors.

The failure occurs specifically while importing `@napi-rs/keyring`.

---

**Additional context**

The Inspector currently performs a top-level import of:

```ts
import { AsyncEntry, findCredentialsAsync } from "@napi-rs/keyring";
```

This import exists in multiple clients (CLI, TUI, and Web).

Those same files also contain logic intended to handle unavailable OS keychains (for example, messages such as "OS keychain is not available...").

However, because the import itself fails, execution never reaches that fallback logic.

It appears this dependency should be loaded lazily (e.g. inside a `try/catch`) so that unsupported platforms such as Android/Termux can still run the Inspector without OS keychain integration.

### PR DESCRIPTION
**Pull request by cliffhall**
Closes #1905
Closes #1852

> **Stacked on #1945** (`v2/fix/keyring-construct-degradation`, which closes #1848). Base is that branch, not `v2/main`, so this diff shows only the lazy-import change. Merge #1945 first; GitHub will retarget this to `v2/main` automatically. The two fix adjacent failure modes in the same file and the second builds on the first's test scaffolding, which is why they're stacked rather than independent.

`@napi-rs/keyring` ships one prebuilt binary per platform triple and throws on import where it has none. On Android / Termux there is no `@napi-rs/keyring-android-arm64`, so the static top-level import at `core/auth/node/secret-store.ts:16` threw during **module evaluation** — the Inspector exited at startup with `Cannot find native binding`, before any of the keychain-unavailable handling *in that same file* could run.

This is one layer earlier than #1848: there the package loaded and `AsyncEntry::new` threw; here the package never loads at all.

**Also closes #1852** ("unable to run the web UI on Windows"), which is the same root cause reached a different way: npm's optional-deps bug ([npm/cli#4828](https://github.com/npm/cli/issues/4828)) drops the platform package on a *supported* triple — typically via an in-place `npx` cache upgrade — and the static import then throws the identical `Cannot find native binding` at startup. That was previously being fixed in #1943, which bundled this change together with #1848's; #1943 is closed as superseded by this stack, and its one unique piece is ported below.

## The change

The static import becomes a cached dynamic one. Two details are deliberate:

- **The outcome is cached, not just the module.** A box without a binary must not re-attempt (and re-throw) resolution on every secret operation — `expectedSecretFields` always includes the OAuth slot, so that would be once per server per `GET /api/servers`.
- **The failure is cached alongside the success** so `set` can name the underlying cause in its `KeychainUnavailableError` rather than reporting a bare "unavailable".

An unloadable package now folds into the same degradation contract as an unreachable keychain: `get` returns `null`, `delete` / `deleteAllForServer` no-op, `set` throws `KeychainUnavailableError` — and is **not** double-wrapped, since the load failure is already typed by the time the catch sees it.

The class doc comment now enumerates all three ways "unavailable" can arrive (package won't load / constructor throws / operation throws), because each of them escaped the contract at some point and the contract is only as good as its narrowest funnel. Also updated the `@napi-rs/keyring` note in `clients/web/server/vite-base-config.ts` to say the load is lazy.

**The `KeychainUnavailableError` message now branches on the cause** (ported from #1943). A missing platform binary has nothing to do with a keyring daemon, so telling that user to install libsecret sends them down the wrong path — when the cause carries the loader's `Cannot find native binding` phrasing, the error instead points at a reinstall and, for `npx`, clearing the npx cache. Every other cause keeps the Linux libsecret / gnome-keyring advice.

There is deliberately **no cache-reset seam** — a platform does not grow a native binary mid-run. Tests reach the unloadable path through a fresh module instead (below).

## Tests

The shared `vi.mock` stub can't express this — it models a keyring that *loads*. The new describe builds on `vi.resetModules()` + `vi.doMock` with a throwing factory and re-imports the module, covering: the module still evaluating at all (the regression itself), `get`, `set` (typed, with the cause appended, not double-wrapped), `delete` / `deleteAllForServer`, and the load-once caching.

One assertion is deliberately by shape rather than literal text: vitest substitutes its own "error when mocking a module" message for a throwing `doMock` factory, so the simulated `Cannot find module ...` string never reaches the store. The test asserts the cause is *appended* (`/Underlying error: .+/`) rather than swallowed; the comment records why. In production the real "Cannot find native binding" text lands in that slot.

Verified red-without / green-with: all six new tests fail against the static import and pass after.

The two hint branches get their own cases, asserted by **direct construction** rather than through the store — for the same `doMock` reason as above, the real loader text can't reach the constructor from the unloadable-package path, so these pin the wording against the message napi-rs actually produces (reinstall hint present and libsecret advice *absent* for a native-binding cause; the reverse for any other).

**Bundling check** — because the fix only works if the dynamic import survives bundling, I confirmed all three built clients keep it as a dynamic import rather than inlining it back to a static one:

```
clients/cli/build/index.js:import("@napi-rs/keyring")
clients/tui/build/index.js:import("@napi-rs/keyring")
clients/web/build/index.js:import("@napi-rs/keyring")
```

## Verification

`npm run ci` green, run in stages:

- `validate` — pass on re-run. The first pass showed two failures in `AppsScreen.test.tsx` and `useServers.test.tsx` (both timing-sensitive, one at 5.9s under full-suite load); both pass in isolation and neither touches the keyring path.
- `coverage` — 4818 passed; `secret-store.ts` at 98.3 / 96.42 / 100 / 100. Same two pre-existing `inspectorClient.test.ts` unhandled rejections noted on #1945, which reproduce identically in a sibling worktree on unmodified code whose CI is green.
- `verify:build-gate` — pass
- `smoke` — all six pass
- `ci:storybook` — 462 passed

No UI change, so no screenshots.

## Not covered here

This makes an unsupported platform *start* and work for non-secret flows; it does not give it secret persistence. The reporter on #1848 raised the same question for containers. Since `SecretStore` is already an interface with `InMemorySecretStore` alongside, a file-backed or explicitly in-memory store is worth considering as its own issue — out of scope for this fix.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01XAR2Nr9kXbrywFNUVoTe9F

### CODE REVIEW

**Comment by cliffhall** [comment]
## Code review

Reviewed the full diff (`+208/-23`, 3 files) against its base branch, and checked the runtime behavior of the real package rather than reasoning only from the mocked tests.

### Overview

Replaces the static top-level `import { AsyncEntry, findCredentialsAsync } from "@napi-rs/keyring"` with a cached dynamic import, so a platform with no prebuilt binary degrades through the existing keychain-unavailable contract instead of crashing during module evaluation.

### Correctness

The mechanism is sound, and a few details are right in ways that are easy to get wrong:

- **`keyringLoad ??= …` is assigned synchronously**, before any `await`, so N concurrent `get`s from `readKeychainEntriesFor`'s `Promise.all` share one in-flight import rather than racing N of them.
- **`.then(onFulfilled, onRejected)` means the cached promise never rejects** — it always resolves to a `KeyringLoad`. No unhandled-rejection hazard from a cached failure nobody awaits.
- **The double-wrap guard in `set` is a real catch, not a hypothetical one.** Throwing `KeychainUnavailableError` from inside the `try` and then re-entering its own `catch` would otherwise nest the prefix twice and push the actual cause a level deeper. Good that it has a dedicated test asserting exactly one prefix.
- **`typeof import("@napi-rs/keyring")` is type-only** and erases cleanly; the bundle check in the description confirms only the dynamic `import(...)` survives in all three clients.

I verified the CJS→ESM interop against the real package rather than trusting the mock:

```
keys: AsyncEntry,Entry,default,findCredentials,findCredentialsAsync,module.exports
AsyncEntry: function | findCredentialsAsync: function
```

So `mod.AsyncEntry` resolves correctly today — same named-export resolution the static import was already relying on. Not a live bug.

### The one thing I'd change

**Validate the module shape in `loadKeyring`, and treat a bad shape as unavailable.**

The namespace check above is reassuring for *today*, but consider the failure mode if it ever stops holding — a package version that moves to a default-only export, a bundler that changes interop handling, or a platform where `cjs-module-lexer` doesn't detect the named exports:

- `keyring.mod.AsyncEntry` is `undefined`
- `new undefined(...)` throws a `TypeError`
- that `TypeError` is caught by the very `catch` that implements graceful degradation
- `get` returns `null`, so **every server's secrets silently vanish and the UI shows an empty list with no error at all**

Nothing in the suite would catch that. The unit tests all run against the stub, so they never exercise the real namespace. And the smokes don't help either: `smoke:web:browser` asserts the "Add Servers" control renders — which *is* the empty state — so a total secret-rehydration failure and a healthy first run look identical to it.

That's a nasty shape for a bug: silent, data-shaped, and invisible to every gate. Cheap fix, in `loadKeyring`:

```ts
keyringLoad ??= import("@napi-rs/keyring").then(
  (mod): KeyringLoad =>
    typeof mod.AsyncEntry === "function" &&
    typeof mod.findCredentialsAsync === "function"
      ? { ok: true, mod }
      : {
          ok: false,
          err: new Error(
            "@napi-rs/keyring loaded but did not expose AsyncEntry / findCredentialsAsync",
          ),
        },
  (err: unknown): KeyringLoad => ({ ok: false, err }),
);
```

That converts a silent empty-list into the same actionable 503 on `set` that every other unavailability produces — which is exactly the contract this PR is about. It's also the one new risk the refactor introduces, so it seems worth closing in the same change.

If you'd rather not, the alternative is an unmocked round-trip test (`set` → `get` → `delete` against the real keyring, skipped when unavailable) so at least one thing in the suite touches the real namespace. The guard is cheaper and fails more usefully.

### Test coverage

Strong. Six cases, and the `vi.resetModules()` + `vi.doMock` approach is the right call — a flag on the shared stub genuinely cannot express "the import itself rejects," and the comment says so rather than leaving the reader wondering why this describe is shaped differently.

- Asserting **the module still evaluates at all** as its own first test is the right framing: that, not any downstream behavior, is the regression.
- The load-once test is a genuine caching assertion, not a tautology — three operations, one attempt.
- The honesty about vitest substituting its own message for a throwing `doMock` factory, with the assertion relaxed to `/Underlying error: .+/` and the reason recorded inline, is better than the alternative of quietly asserting something weaker with no explanation. It does mean the real "Cannot find native binding" text is never exercised end to end; acceptable, and now documented.

`secret-store.ts` at 98.3 / 96.42 / 100 / 100.

### Nits

- **Comment run-on** in the test file: the block explaining the re-imported module's distinct class identity runs straight into "The real-world message on Termux…" with no separator, so the two read as one comment. The second belongs to `LOAD_ERROR` — a blank line, or moving it directly above the constant, fixes it.
- `LOAD_ERROR` is now thrown but never matched against. That's fine and deliberate, but a reader may go looking for the assertion that uses it; the comment mostly covers this.

### Conventions, performance, security

- TypeScript rules honored — the discriminated `KeyringLoad` union is the right shape here, no `any`, no casts.
- The `vite-base-config.ts` comment update is the kind of doc-sync the project asks for and is easy to forget; good that it's in the same PR.
- Performance: one extra module resolution on the first secret operation of the process, cached thereafter. Negligible, and it removes the resolution from startup.
- The deliberate absence of a cache-reset seam is correct and well-argued — a platform doesn't grow a native binary mid-run, and the reasoning is recorded where the next person will look. Note this contrasts with the *keychain-reachability* case, which genuinely can change mid-process; the doc comment could arguably say why the two are cached differently, but it's a fine distinction and the current text isn't wrong.
- Security: no new surface. Secrets still never touch disk on this path.

### Verdict

Approve modulo the shape guard, which I'd fold in before merge — it's a few lines and it closes the only new silent-failure path this refactor opens. Everything else is a nit.

*Note: I authored this PR, so treat the review as a structured self-check rather than independent sign-off — the shape-guard finding in particular came out of testing the real package against the mock's assumptions, which the original work didn't do.*

File: clients/web/src/test/integration/auth/node/secret-store.test.ts [hunk 1]
```diff
@@ -7,8 +7,14 @@
  * so the suite stubs the native side and asserts the tolerance contract
  * (`get` returns null on failure, destructive ops no-op, `set` is the
  * one operation that hard-fails with `KeychainUnavailableError`).
+ *
+ * The contract has three entry points for "unavailable" and the suite
+ * covers all three: the operation throwing, `AsyncEntry`'s constructor
+ * throwing (#1848), and the package failing to load at all (#1905). The
+ * last one can't use the shared stub — it needs the *import* to reject —
+ * so it lives in its own describe built on `vi.resetModules()`.
```
[the remark this answers is not in the document]
Comment (cliffhall) [reply clients/web/src/test/integration/auth/node/secret-store.test.ts]: Fixed in 0fb3e1c4 — good catch, and it was a real inconsistency rather than a cosmetic one: `secret-store.ts`'s own enumeration was updated to four when the shape check landed, but this header was left at three. An exhaustive-sounding list that omits the case a describe further down the same file covers is exactly the kind of comment that misleads.

It now reads four, names the wrong-shape case, and explains why the last *two* need their own describes rather than the shared stub — one needs the import to reject, the other needs it to resolve to a namespace the stub cannot express.

I also swept both files plus `vite-base-config.ts` for any other stale count; that header was the only one.

**Comment by cliffhall** [comment]
Both suppressed comments from the last Copilot pass were right and are fixed in 1917435a.

**1. Wrong-shape cause got the libsecret advice.** This was the sharper of the two: the shape check I added introduced a cause that fell straight through to `On Linux, install libsecret / gnome-keyring` — advice that cannot fix a packaging mismatch, and that on Windows or macOS points at something which does not exist. It is the *same* wrong-advice bug the native-binding branch was added to fix, reintroduced by the guard itself one commit later.

Hint selection now lives in a `hintFor` function where the libsecret line is the explicit fallback rather than the default, so a new cause landing there is a visible choice instead of a silent inheritance. The shape failure is now a distinct `KeyringModuleShapeError` matched **by type** rather than by message: it is our own error, so re-parsing text we just wrote would be pointless indirection — the native-binding branch string-matches only because that phrasing comes from the napi-rs loader. New test asserts the shape cause gets the reinstall advice and explicitly *not* libsecret.

**2. Test title overstated what the guard does.** Also correct, and it is a claim I had already walked back elsewhere: the guard does not prevent `get` from returning `null` — that is the read-tolerance contract and it behaves identically with or without the check. What changes is that `set` names the real cause instead of reporting `AsyncEntry is not a constructor`. The comments and commit message said so; the title still said "rather than returning null secrets", so the file contradicted itself. Retitled to `hard-fails set ... (get still returns null by contract)`.

Also updated the `KeychainUnavailableError` doc to enumerate all three causes and why each needs different advice.

Verification: `validate:core` + `validate:web` pass (3728 unit), coverage 4827 passed with `secret-store.ts` at 98.63 / 97.22 / 100 / 100, `tsc -b` clean. The nonzero exit on `coverage:web` is the two pre-existing `CONNECTION_CLOSED` unhandled rejections in `inspectorClient.test.ts`, which reproduce identically on the base commit — zero test failures and no threshold errors in the run itself.

**Comment by cliffhall** [comment]
Right again, and fixed in dc653638 — this is the third instance of one mistake, which is the more useful signal than the individual bug.

The shape check fails two ways: the members are absent, or *reading* them throws (a Proxy-backed namespace, which is what vitest's module mock does). Only the first carried `KeyringModuleShapeError`; the catch path returned the raw error, so it fell through to `install libsecret` — the identical wrong-remedy bug as the two commits before it, one branch further along.

Both paths now carry the type. `KeyringModuleShapeError` takes a detail string plus a standard `cause`, so the throwing path reads `its exports could not be read: <original>` — the packaging hint is earned without losing the underlying failure.

**What I take from three in a row:** the shape was wrong, not just the branch. Making libsecret an explicit fallback in `hintFor` last round did not stop me from adding a *second exit* that skipped it. So the invariant is now pinned by tests rather than by structure — one asserts both construction paths produce the same hint, another asserts the throwing-namespace case reaches the user as a packaging problem and explicitly not as libsecret. The next cause that forgets its remediation fails a test instead of needing a reviewer to spot it.

I also verified the negative assertion actually asserts — `rejects.not.toThrow` can pass vacuously if chained wrong, so I inverted the regex, confirmed the test fails, and restored it.

Verification: `validate:core` + `validate:web` pass (3728 unit), coverage 4828 passed, zero test failures, `secret-store.ts` at 98.63 / 94.73 / 100 / 100 (branches down from 97.22, still well over the 90 gate — the uncovered arm is the non-`Error` cause stringification). `tsc -b` clean. The nonzero `coverage:web` exit is still the two pre-existing `CONNECTION_CLOSED` rejections that reproduce on the base commit.
